set_property PACKAGE_PIN C17 [get_ports reset_rtl_0_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl_0_0]
set_property PACKAGE_PIN D18 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]

#DAC

set_property PACKAGE_PIN Y19 [get_ports {dZmodDAC_Data_0[0]}]
set_property PACKAGE_PIN Y18 [get_ports {dZmodDAC_Data_0[1]}]
set_property PACKAGE_PIN AB22 [get_ports {dZmodDAC_Data_0[2]}]
set_property PACKAGE_PIN AB20 [get_ports {dZmodDAC_Data_0[3]}]
set_property PACKAGE_PIN AA18 [get_ports {dZmodDAC_Data_0[4]}]
set_property PACKAGE_PIN AA19 [get_ports {dZmodDAC_Data_0[5]}]
set_property PACKAGE_PIN Y21 [get_ports {dZmodDAC_Data_0[6]}]
set_property PACKAGE_PIN Y20 [get_ports {dZmodDAC_Data_0[7]}]
set_property PACKAGE_PIN V15 [get_ports {dZmodDAC_Data_0[8]}]
set_property PACKAGE_PIN V14 [get_ports {dZmodDAC_Data_0[9]}]
set_property PACKAGE_PIN AB15 [get_ports {dZmodDAC_Data_0[10]}]
set_property PACKAGE_PIN AB14 [get_ports {dZmodDAC_Data_0[11]}]
set_property PACKAGE_PIN W13 [get_ports {dZmodDAC_Data_0[12]}]
set_property PACKAGE_PIN V13 [get_ports {dZmodDAC_Data_0[13]}]

set_property IOSTANDARD LVCMOS18 [get_ports -filter { name =~ dZmodDAC_Data_0*}]

set_property PACKAGE_PIN W16 [get_ports ZmodDAC_Clkin_0]
set_property IOSTANDARD LVCMOS18 [get_ports ZmodDAC_Clkin_0]
set_property PACKAGE_PIN W17 [get_ports ZmodDAC_ClkIO_0]
set_property IOSTANDARD LVCMOS18 [get_ports ZmodDAC_ClkIO_0]

#DAC SPI
set_property PACKAGE_PIN Y14 [get_ports sZmodDAC_SDIO_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodDAC_SDIO_0]
set_property DRIVE 4 [get_ports sZmodDAC_SDIO_0]
set_property PACKAGE_PIN AA14 [get_ports sZmodDAC_CS_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodDAC_CS_0]
set_property DRIVE 4 [get_ports sZmodDAC_CS_0]
set_property PACKAGE_PIN AA13 [get_ports sZmodDAC_SCLK_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodDAC_SCLK_0]
set_property DRIVE 4 [get_ports sZmodDAC_SCLK_0]

set_property PACKAGE_PIN W15 [get_ports sZmodDAC_SetFS1_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodDAC_SetFS1_0]
set_property PACKAGE_PIN Y15 [get_ports sZmodDAC_SetFS2_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodDAC_SetFS2_0]
set_property PACKAGE_PIN Y13 [get_ports sZmodDAC_Reset_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodDAC_Reset_0]
set_property PACKAGE_PIN AA22 [get_ports sZmodDAC_EnOut_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodDAC_EnOut_0]

#Zmod ADC

#Relays
set_property PACKAGE_PIN T16 [get_ports sZmodCh1CouplingH_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodCh1CouplingH_0]
set_property PACKAGE_PIN T17 [get_ports sZmodCh1CouplingL_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodCh1CouplingL_0]
set_property PACKAGE_PIN R19 [get_ports sZmodCh2CouplingH_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodCh2CouplingH_0]
set_property PACKAGE_PIN T19 [get_ports sZmodCh2CouplingL_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodCh2CouplingL_0]
set_property PACKAGE_PIN N15 [get_ports sZmodCh1GainH_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodCh1GainH_0]
set_property PACKAGE_PIN P15 [get_ports sZmodCh1GainL_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodCh1GainL_0]
set_property PACKAGE_PIN P17 [get_ports sZmodCh2GainH_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodCh2GainH_0]
set_property PACKAGE_PIN P18 [get_ports sZmodCh2GainL_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodCh2GainL_0]
set_property PACKAGE_PIN J20 [get_ports sZmodRelayComH_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodRelayComH_0]
set_property PACKAGE_PIN K21 [get_ports sZmodRelayComL_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodRelayComL_0]
# ADC
set_property PACKAGE_PIN R18 [get_ports sZmodADC_SDIO_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodADC_SDIO_0]
set_property DRIVE 4 [get_ports sZmodADC_SDIO_0]
set_property PACKAGE_PIN M21 [get_ports sZmodADC_CS_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodADC_CS_0]
set_property DRIVE 4 [get_ports sZmodADC_CS_0]
set_property PACKAGE_PIN T18 [get_ports sZmodADC_Sclk_0]
set_property IOSTANDARD LVCMOS18 [get_ports sZmodADC_Sclk_0]
set_property DRIVE 4 [get_ports sZmodADC_Sclk_0]
set_property PACKAGE_PIN M22 [get_ports iZmodSync_0]
set_property IOSTANDARD LVCMOS18 [get_ports iZmodSync_0]
set_property DRIVE 4 [get_ports iZmodSync_0]
set_property SLEW SLOW [get_ports iZmodSync_0]
set_property PACKAGE_PIN M19 [get_ports ZmodDcoClk_0]
set_property IOSTANDARD LVCMOS18 [get_ports ZmodDcoClk_0]

set_property IOSTANDARD DIFF_SSTL18_I [get_ports -filter { name =~ ZmodAdcClkIn* }]
set_property PACKAGE_PIN N19 [get_ports ZmodAdcClkIn_p_0]
set_property PACKAGE_PIN N20 [get_ports ZmodAdcClkIn_n_0]
set_property SLEW SLOW [get_ports -filter { name =~ ZmodAdcClkIn* }]

#14 bit
set_property PACKAGE_PIN N22 [get_ports {dZmodADC_Data_0[0]}]
set_property PACKAGE_PIN L21 [get_ports {dZmodADC_Data_0[1]}]
set_property PACKAGE_PIN R16 [get_ports {dZmodADC_Data_0[2]}]
set_property PACKAGE_PIN J18 [get_ports {dZmodADC_Data_0[3]}]
set_property PACKAGE_PIN K18 [get_ports {dZmodADC_Data_0[4]}]
set_property PACKAGE_PIN L19 [get_ports {dZmodADC_Data_0[5]}]
set_property PACKAGE_PIN L18 [get_ports {dZmodADC_Data_0[6]}]
set_property PACKAGE_PIN L22 [get_ports {dZmodADC_Data_0[7]}]
set_property PACKAGE_PIN K20 [get_ports {dZmodADC_Data_0[8]}]
set_property PACKAGE_PIN P16 [get_ports {dZmodADC_Data_0[9]}]
set_property PACKAGE_PIN K19 [get_ports {dZmodADC_Data_0[10]}]
set_property PACKAGE_PIN J22 [get_ports {dZmodADC_Data_0[11]}]
set_property PACKAGE_PIN J21 [get_ports {dZmodADC_Data_0[12]}]
set_property PACKAGE_PIN P22 [get_ports {dZmodADC_Data_0[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports -filter { name =~ dZmodADC_Data_0*}]