set_property PACKAGE_PIN C17 [get_ports reset_rtl_0_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl_0_0]
set_property PACKAGE_PIN D18 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]


set_property PACKAGE_PIN T16 [get_ports SC1_AC_H_0]
set_property IOSTANDARD LVCMOS18 [get_ports SC1_AC_H_0]
set_property PACKAGE_PIN T17 [get_ports SC1_AC_L_0]
set_property IOSTANDARD LVCMOS18 [get_ports SC1_AC_L_0]
set_property PACKAGE_PIN R19 [get_ports SC2_AC_H_0]
set_property IOSTANDARD LVCMOS18 [get_ports SC2_AC_H_0]
set_property PACKAGE_PIN T19 [get_ports SC2_AC_L_0]
set_property IOSTANDARD LVCMOS18 [get_ports SC2_AC_L_0]
set_property PACKAGE_PIN N15 [get_ports SC1_GAIN_H_0]
set_property IOSTANDARD LVCMOS18 [get_ports SC1_GAIN_H_0]
set_property PACKAGE_PIN P15 [get_ports SC1_GAIN_L_0]
set_property IOSTANDARD LVCMOS18 [get_ports SC1_GAIN_L_0]
set_property PACKAGE_PIN P17 [get_ports SC2_GAIN_H_0]
set_property IOSTANDARD LVCMOS18 [get_ports SC2_GAIN_H_0]
set_property PACKAGE_PIN P18 [get_ports SC2_GAIN_L_0]
set_property IOSTANDARD LVCMOS18 [get_ports SC2_GAIN_L_0]
set_property PACKAGE_PIN J20 [get_ports SC_COM_H_0]
set_property IOSTANDARD LVCMOS18 [get_ports SC_COM_H_0]
set_property PACKAGE_PIN K21 [get_ports SC_COM_L_0]
set_property IOSTANDARD LVCMOS18 [get_ports SC_COM_L_0]
# ADC 
set_property PACKAGE_PIN R18 [get_ports sdio_sc_0]
set_property IOSTANDARD LVCMOS18 [get_ports sdio_sc_0]
set_property DRIVE 4 [get_ports sdio_sc_0]
set_property PACKAGE_PIN M21 [get_ports cs_sc1_0]
set_property IOSTANDARD LVCMOS18 [get_ports cs_sc1_0]
set_property DRIVE 4 [get_ports cs_sc1_0]
set_property PACKAGE_PIN T18 [get_ports sclk_sc_0]
set_property IOSTANDARD LVCMOS18 [get_ports sclk_sc_0]
set_property DRIVE 4 [get_ports sclk_sc_0]
set_property PACKAGE_PIN M22 [get_ports ADC_SYNC_0]
set_property IOSTANDARD LVCMOS18 [get_ports -filter { name =~ ADC_SYNC* }]
set_property DRIVE 4 [get_ports -filter { name =~ ADC_SYNC* }]
set_property SLEW SLOW [get_ports -filter { name =~ ADC_SYNC* }]
set_property PACKAGE_PIN M19 [get_ports ADC_DCO_0]
set_property IOSTANDARD LVCMOS18 [get_ports -filter { name =~ ADC_DCO* }]

set_property IOSTANDARD DIFF_SSTL18_I [get_ports -filter { name =~ CLKIN_ADC* }]
set_property PACKAGE_PIN N19 [get_ports CLKIN_ADC_P_0]
set_property PACKAGE_PIN N20 [get_ports CLKIN_ADC_N_0]
set_property SLEW SLOW [get_ports -filter { name =~ CLKIN_ADC* }]

set_property PACKAGE_PIN N22 [get_ports {ADC_DATA_0[0]}]
set_property PACKAGE_PIN L21 [get_ports {ADC_DATA_0[1]}]
set_property PACKAGE_PIN R16 [get_ports {ADC_DATA_0[2]}]
set_property PACKAGE_PIN J18 [get_ports {ADC_DATA_0[3]}]
set_property PACKAGE_PIN K18 [get_ports {ADC_DATA_0[4]}]
set_property PACKAGE_PIN L19 [get_ports {ADC_DATA_0[5]}]
set_property PACKAGE_PIN L18 [get_ports {ADC_DATA_0[6]}]
set_property PACKAGE_PIN L22 [get_ports {ADC_DATA_0[7]}]
set_property PACKAGE_PIN K20 [get_ports {ADC_DATA_0[8]}]
set_property PACKAGE_PIN P16 [get_ports {ADC_DATA_0[9]}]
set_property PACKAGE_PIN K19 [get_ports {ADC_DATA_0[10]}]
set_property PACKAGE_PIN J22 [get_ports {ADC_DATA_0[11]}]
set_property PACKAGE_PIN J21 [get_ports {ADC_DATA_0[12]}]
set_property PACKAGE_PIN P22 [get_ports {ADC_DATA_0[13]}]

set_property IOSTANDARD LVCMOS18 [get_ports -filter { name =~ ADC_DATA*}]

create_clock -period 10.000 -name ADC_DCO_0 -waveform {0.000 5.000} [get_ports ADC_DCO_0]
create_generated_clock -name CLKIN_ADC_P_0 -source [get_pins design_1_i/ZmodADC1410_Controll_0/U0/InstADC_ClkODDR/C] -divide_by 1 [get_ports CLKIN_ADC_P_0]

set_input_delay -clock [get_clocks ADC_DCO_0] -clock_fall -min -add_delay 3.240 [get_ports {ADC_DATA_0[*]}]
set_input_delay -clock [get_clocks ADC_DCO_0] -clock_fall -max -add_delay 5.440 [get_ports {ADC_DATA_0[*]}]
set_input_delay -clock [get_clocks ADC_DCO_0] -min -add_delay 3.240 [get_ports {ADC_DATA_0[*]}]
set_input_delay -clock [get_clocks ADC_DCO_0] -max -add_delay 5.440 [get_ports {ADC_DATA_0[*]}]

#DAC

set_property PACKAGE_PIN Y19 [get_ports {DAC_DATA_0[0]}]
set_property PACKAGE_PIN Y18 [get_ports {DAC_DATA_0[1]}]
set_property PACKAGE_PIN AB22 [get_ports {DAC_DATA_0[2]}]
set_property PACKAGE_PIN AB20 [get_ports {DAC_DATA_0[3]}]
set_property PACKAGE_PIN AA18 [get_ports {DAC_DATA_0[4]}]
set_property PACKAGE_PIN AA19 [get_ports {DAC_DATA_0[5]}]
set_property PACKAGE_PIN Y21 [get_ports {DAC_DATA_0[6]}]
set_property PACKAGE_PIN Y20 [get_ports {DAC_DATA_0[7]}]
set_property PACKAGE_PIN V15 [get_ports {DAC_DATA_0[8]}]
set_property PACKAGE_PIN V14 [get_ports {DAC_DATA_0[9]}]
set_property PACKAGE_PIN AB15 [get_ports {DAC_DATA_0[10]}]
set_property PACKAGE_PIN AB14 [get_ports {DAC_DATA_0[11]}]
set_property PACKAGE_PIN W13 [get_ports {DAC_DATA_0[12]}]
set_property PACKAGE_PIN V13 [get_ports {DAC_DATA_0[13]}]

set_property IOSTANDARD LVCMOS18 [get_ports -filter { name =~ DAC_DATA*}]

set_property PACKAGE_PIN W16 [get_ports DAC_CLKIN_0]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CLKIN_0]
set_property PACKAGE_PIN W17 [get_ports DAC_CLKIO_0]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CLKIO_0]

#DAC SPI
set_property PACKAGE_PIN Y14 [get_ports DAC_SDIO_0]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SDIO_0]
set_property DRIVE 4 [get_ports DAC_SDIO_0]
set_property PACKAGE_PIN AA14 [get_ports DAC_CS_0]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_CS_0]
set_property DRIVE 4 [get_ports DAC_CS_0]
set_property PACKAGE_PIN AA13 [get_ports DAC_SCLK_0]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SCLK_0]
set_property DRIVE 4 [get_ports DAC_SCLK_0]

set_property PACKAGE_PIN W15 [get_ports DAC_SET_FS1_0]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SET_FS1_0]
set_property PACKAGE_PIN Y15 [get_ports DAC_SET_FS2_0]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SET_FS2_0]
set_property PACKAGE_PIN Y13 [get_ports DAC_RESET_0]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_RESET_0]
set_property PACKAGE_PIN AA22 [get_ports DAC_EN_0]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_EN_0]


create_generated_clock -name DAC_CLKIN_0 -source [get_pins design_1_i/ZmodDAC1411_Controll_0/U0/InstDAC_ClkinODDR/C] -divide_by 1 [get_ports DAC_CLKIN_0]
create_generated_clock -name DAC_CLKIO_0 -source [get_pins design_1_i/ZmodDAC1411_Controll_0/U0/InstDAC_ClkIO_ODDR/C] -divide_by 1 [get_ports DAC_CLKIO_0]
set_output_delay -clock [get_clocks DAC_CLKIN_0] -clock_fall -min -add_delay -1.200 [get_ports {DAC_DATA_0[*]}]
set_output_delay -clock [get_clocks DAC_CLKIN_0] -clock_fall -max -add_delay 0.250 [get_ports {DAC_DATA_0[*]}]
set_output_delay -clock [get_clocks DAC_CLKIN_0] -min -add_delay -1.100 [get_ports {DAC_DATA_0[*]}]
set_output_delay -clock [get_clocks DAC_CLKIN_0] -max -add_delay 0.130 [get_ports {DAC_DATA_0[*]}]

